# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kics < Formula
  desc "Find security vulnerabilities, compliance issues, and infrastructure misconfigurations in your IaC"
  homepage "https://github.com/Checkmarx/kics"
  version "1.4.2"
  license "Apache"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.2/kics_1.4.2_darwin_x64.tar.gz"
      sha256 "d0d05e25a3d03736f3417e342263547621cf455c4e5b5186d78ddd3695155152"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.2/kics_1.4.2_darwin_arm64.tar.gz"
      sha256 "cc66a57b4b1d34754cb499eda5905d633efdd7b9f91739ae5c5c7d5fac3852cb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.2/kics_1.4.2_linux_x64.tar.gz"
      sha256 "4f174040528a144e5cde886fa3922a0183447b697b5fc5009a4252596e123057"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.2/kics_1.4.2_linux_arm64.tar.gz"
      sha256 "0fe4f659a0f9b399ee19db95dfdf85800ff39d0907f2ffca9df644f54aa48a97"
    end
  end

  def caveats
    <<~EOS
      KICS queries are placed under #{pkgshare}/assets/queries

      To use KICS default queries add KICS_QUERIES_PATH env to your ~/.zshrc or ~/.zprofile:
          "echo 'export KICS_QUERIES_PATH=#{pkgshare}/assets/queries' >> ~/.zshrc"

      usage of CLI flag --queries-path takes precedence.
    EOS
  end

  def install
    pkgshare.mkpath
    cp_r "assets", pkgshare
    bin.install "kics"
  end

  test do
    system "#{bin}/kics version"
  end
end
