# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kics < Formula
  desc "Find security vulnerabilities, compliance issues, and infrastructure misconfigurations in your IaC"
  homepage "https://github.com/Checkmarx/kics"
  version "1.4.6"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6/kics_1.4.6_darwin_x64.tar.gz"
      sha256 "839359b67fe9e9c49a23ab2fcad5198e0f28b8476990081b7f4430890c2070d1"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6/kics_1.4.6_darwin_arm64.tar.gz"
      sha256 "b3f380b78b4cb9a570238e49ca76c6ddabdd6e7b111afc9a45d8bb9a2688bad5"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6/kics_1.4.6_linux_arm64.tar.gz"
      sha256 "483a5d3f74eea7e6e2dae4677b41cfaafc938574dac6ddd25edec4515baffa96"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6/kics_1.4.6_linux_x64.tar.gz"
      sha256 "0ec255caf17052059cfe882952544aad840cadcde1d4d5a78f44d6d5866ac199"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
  end

  def caveats
    <<~EOS
      KICS queries are placed under #{pkgshare}/assets/queries

      To use KICS default queries add KICS_QUERIES_PATH env to your ~/.zshrc or ~/.zprofile:
          "echo 'export KICS_QUERIES_PATH=#{pkgshare}/assets/queries' >> ~/.zshrc"

      usage of CLI flag --queries-path takes precedence.
    EOS
  end

  test do
    system "#{bin}/kics version"
  end
end
