# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kics < Formula
  desc "Find security vulnerabilities, compliance issues, and infrastructure misconfigurations in your IaC"
  homepage "https://github.com/Checkmarx/kics"
  version "1.4.6-1"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6-1/kics_1.4.6-1_darwin_x64.tar.gz"
      sha256 "fe63ff328c0c2e71a1282d9449ca7294519c108f78b0708305a49667ee8ed929"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6-1/kics_1.4.6-1_darwin_arm64.tar.gz"
      sha256 "a2ac81392bd4ae22d387dff689606bf0fd17797bdb780ea7aee4eec96e8df549"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6-1/kics_1.4.6-1_linux_x64.tar.gz"
      sha256 "f6e9d70d4c03207fdd30dbb32a283ec066a34dc05cca5250f51bcd4d62c26fd3"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Checkmarx/kics/releases/download/v1.4.6-1/kics_1.4.6-1_linux_arm64.tar.gz"
      sha256 "5f6d2eb52bdaae35c968ed5a19215b347ed0988fe44d78cccf8d28d50d2f539e"

      def install
        pkgshare.mkpath
        cp_r "assets", pkgshare
        bin.install "kics"
      end
    end
  end

  def caveats
    <<~EOS
      KICS queries are placed under #{pkgshare}/assets/queries

      To use KICS default queries add KICS_QUERIES_PATH env to your ~/.zshrc or ~/.zprofile:
          "echo 'export KICS_QUERIES_PATH=#{pkgshare}/assets/queries' >> ~/.zshrc"

      usage of CLI flag --queries-path takes precedence.
    EOS
  end

  test do
    system "#{bin}/kics version"
  end
end
